server {
    listen 80;
    listen [::]:80;
    server_name calclyo.com www.calclyo.com;

    root /var/www/calclyo.com/platform/public;
    index index.php index.html;
    charset utf-8;
    add_header X-Served-By "jarvis-rpi-calclyo" always;

    access_log /var/log/nginx/calclyo.com.access.log;
    error_log /var/log/nginx/calclyo.com.error.log;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
