server {
    listen 80;
    listen [::]:80;
    server_name tools.bakerysoft.net;

    root /var/www/tools.bakerysoft.net;
    index index.html;
    add_header X-Served-By "jarvis-rpi-nginx-tools" always;

    access_log /var/log/nginx/tools.bakerysoft.net.access.log;
    error_log /var/log/nginx/tools.bakerysoft.net.error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
